name: Setup Standard Workflow
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Enable Corepack
      shell: bash
      run: corepack enable && corepack install
    - name: Print versions
      shell: bash
      run: node --version && pnpm --version
    - name: Get pnpm store directory path
      id: pnpm-cache-dir-path
      shell: bash
      run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - name: Install project dependencies
      shell: bash
      run: pnpm install
