name: Solid Vite Pipeline
on:
  workflow_call:
    inputs:
      publish:
        description: Publish?
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      publish:
        description: Publish?
        required: false
        type: boolean
        default: false
defaults:
  run:
    working-directory: packages/frameworks/solid-vite
jobs:
  solid-vite-workflow:
    runs-on: ubuntu-latest
    name: Lib workflow
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check bundling
        run: pnpm check
        working-directory: packages/frameworks/solid-vite
      - name: Publish to NPM
        if: inputs.publish
        run: pnpm publish
        working-directory: packages/frameworks/solid-vite
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
