name: Solid Renderer Pipeline
on:
  pull_request:
    branches:
      - '*'
    paths:
      - packages/renderers/solid/**
  push:
    branches:
      - main
    paths:
      - packages/renderers/solid/**
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish:
        description: Publish?
        required: false
        type: boolean
        default: false
defaults:
  run:
    working-directory: packages/renderers/solid
jobs:
  solid-workflow:
    runs-on: ubuntu-latest
    name: Lib workflow
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check bundling
        run: pnpm check
        working-directory: packages/renderers/solid
      - name: Publish to NPM
        if: github.event_name == 'release' || inputs.publish
        run: pnpm publish
        working-directory: packages/renderers/solid
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  solid-vite-workflow:
    needs: solid-workflow
    uses: ./.github/workflows/solid-vite.yml
    with:
      publish: ${{ (github.event_name == 'release') || (inputs.publish == true) }}
    secrets: inherit
